import type { Contest, LeaderboardEntry, Problem, User } from '../types'

const users: User[] = [
  { id: 'u1', username: 'qzmalekuz',   email: 'qzmalekuz@kodezilla.io', rating: 1842, rank: 2  },
  { id: 'u2', username: 'loopqueen',   email: 'loop@arena.dev',         rating: 1765, rank: 5  },
  { id: 'u3', username: 'stackstorm',  email: 'stack@arena.dev',        rating: 1912, rank: 1  },
  { id: 'u4', username: 'byteracer',   email: 'byte@arena.dev',         rating: 1780, rank: 4  },
  { id: 'u5', username: 'nullpointer', email: 'null@arena.dev',         rating: 1698, rank: 6  },
  { id: 'u6', username: 'recursor',    email: 'rec@arena.dev',          rating: 1655, rank: 7  },
  { id: 'u7', username: 'heapify',     email: 'heap@arena.dev',         rating: 1820, rank: 3  },
  { id: 'u8', username: 'sigmagrind',  email: 'sigma@arena.dev',        rating: 1610, rank: 8  },
  { id: 'u9', username: 'bitshift',    email: 'bit@arena.dev',          rating: 1580, rank: 9  },
  { id: 'u10', username: 'memoize',    email: 'memo@arena.dev',         rating: 1540, rank: 10 },
]

const problemPool: Problem[] = [
  {
    id: 'p1',
    title: 'Binary Search Range',
    difficulty: 'easy',
    tags: ['binary-search'],
    points: 100,
    timeLimit: '1 s',
    memoryLimit: '256 MB',
    statement: 'You are given a sorted array of N distinct integers and Q queries. For each query, given two integers L and R, count the number of elements in the array that fall within the inclusive range [L, R].',
    inputFormat: 'The first line contains two integers N and Q — the size of the array and the number of queries.\nThe second line contains N space-separated integers in strictly increasing order.\nEach of the next Q lines contains two integers L and R.',
    outputFormat: 'For each query, output a single integer — the count of elements in [L, R].',
    constraints: [
      '1 ≤ N, Q ≤ 10^5',
      '-10^9 ≤ a[i] ≤ 10^9',
      '-10^9 ≤ L ≤ R ≤ 10^9',
    ],
    examples: [
      {
        input: '5 3\n1 3 5 7 9\n2 6\n1 9\n4 8',
        output: '2\n5\n2',
        explanation: 'Query [2,6]: elements 3 and 5 are in range → 2. Query [1,9]: all 5 elements → 5. Query [4,8]: elements 5 and 7 → 2.',
      },
      {
        input: '3 1\n10 20 30\n15 25',
        output: '1',
      },
    ],
    note: 'Use lower_bound and upper_bound (or equivalent) to answer each query in O(log N). A brute-force O(N·Q) solution will TLE.',
  },
  {
    id: 'p2',
    title: 'Shortest Teleport Path',
    difficulty: 'medium',
    tags: ['graphs', 'bfs'],
    points: 250,
    timeLimit: '2 s',
    memoryLimit: '256 MB',
    statement: 'A city has N nodes and M bidirectional roads. Some pairs of nodes are connected by teleporters — instant travel at zero cost. Normal roads have a travel time of 1 unit. Find the minimum travel time from node 1 to node N.\n\nTeleporters are free to use but each teleporter link can only be used once per journey.',
    inputFormat: 'The first line contains N, M, and T — nodes, roads, and teleporter links.\nNext M lines each contain two integers u and v (a road between u and v, cost 1).\nNext T lines each contain two integers u and v (a teleporter between u and v, cost 0).',
    outputFormat: 'A single integer — the minimum time to travel from node 1 to node N. If impossible, output -1.',
    constraints: [
      '2 ≤ N ≤ 10^5',
      '0 ≤ M ≤ 2×10^5',
      '0 ≤ T ≤ 10^5',
      'Edges are bidirectional',
    ],
    examples: [
      {
        input: '4 3 1\n1 2\n2 3\n3 4\n1 4',
        output: '0',
        explanation: 'The teleporter connects node 1 directly to node 4, so the cost is 0.',
      },
      {
        input: '5 4 1\n1 2\n2 3\n3 4\n4 5\n2 4',
        output: '2',
        explanation: 'Path: 1→2 (cost 1) →teleport→ 4 (cost 0) →5 (cost 1) = total 2.',
      },
    ],
    note: 'Model this as a 0-1 BFS: teleporter edges have weight 0 (front of deque) and roads have weight 1 (back of deque).',
  },
  {
    id: 'p3',
    title: 'Segment Tree Beats',
    difficulty: 'hard',
    tags: ['segment-tree'],
    points: 500,
    timeLimit: '3 s',
    memoryLimit: '512 MB',
    statement: 'You are given an array of N integers. You must support two types of operations:\n\n1. Chmin(l, r, v): for all i in [l, r], set a[i] = min(a[i], v).\n2. Query(l, r): output the sum of all elements in [l, r].\n\nProcess all operations efficiently.',
    inputFormat: 'First line: integers N and Q.\nSecond line: N integers — the initial array.\nNext Q lines: either "1 l r v" for a Chmin operation, or "2 l r" for a sum query.',
    outputFormat: 'For each query of type 2, output the sum on a separate line.',
    constraints: [
      '1 ≤ N, Q ≤ 5×10^5',
      '1 ≤ a[i] ≤ 10^9',
      '1 ≤ l ≤ r ≤ N',
      '1 ≤ v ≤ 10^9',
    ],
    examples: [
      {
        input: '5 4\n5 3 8 2 7\n1 1 3 4\n2 1 5\n1 2 5 3\n2 1 5',
        output: '19\n15',
        explanation: 'After Chmin(1,3,4): array = [4,3,4,2,7], sum = 20... wait, query gives sum of all 5 = 4+3+4+2+7 = 20. After Chmin(2,5,3): [4,3,3,2,3], sum = 15.',
      },
    ],
    note: 'This problem requires the "Segment Tree Beats" (Ji Driver Segmentation) technique. The amortized complexity is O((N+Q) log² N).',
  },
  {
    id: 'p4',
    title: 'Rolling Hash Duel',
    difficulty: 'medium',
    tags: ['strings'],
    points: 300,
    timeLimit: '1 s',
    memoryLimit: '256 MB',
    statement: 'Given a string S and Q queries, each query asks: are the substrings S[l1..r1] and S[l2..r2] equal? Answer each query in O(1) after O(N) preprocessing using polynomial rolling hash.',
    inputFormat: 'First line: string S of length N (lowercase English letters).\nSecond line: integer Q.\nNext Q lines: four integers l1 r1 l2 r2 (1-indexed, inclusive).',
    outputFormat: 'For each query, output "YES" if the substrings are equal, "NO" otherwise.',
    constraints: [
      '1 ≤ N ≤ 10^6',
      '1 ≤ Q ≤ 10^5',
      '1 ≤ l1 ≤ r1 ≤ N',
      '1 ≤ l2 ≤ r2 ≤ N',
      'Substrings have equal length: r1-l1 = r2-l2',
    ],
    examples: [
      {
        input: 'abacaba\n3\n1 3 5 7\n1 4 1 4\n2 4 4 6',
        output: 'YES\nYES\nNO',
        explanation: 'S[1..3]="aba" == S[5..7]="aba" → YES. S[1..4]="abac" == S[1..4]="abac" → YES. S[2..4]="bac" vs S[4..6]="cab" → NO.',
      },
    ],
    note: 'Use double hashing (two different bases and mods) to avoid hash collisions. A single hash may fail on adversarial inputs.',
  },
]

export const contests: Contest[] = [
  {
    id: 'c1',
    title: 'Night Sprint 42',
    description: 'Fast-paced 90 min round with implementation-heavy tasks and tight time constraints.',
    startTime: '2026-04-20T17:00:00.000Z',
    endTime: '2026-04-20T18:30:00.000Z',
    participantCount: 862,
    problems: [problemPool[0], problemPool[1], problemPool[3]],
    isPublic: true,
    tags: ['implementation', 'greedy'],
  },
  {
    id: 'c2',
    title: 'Graph Masters Open',
    description: 'Weighted paths, shortest routes, and dynamic constraints across graph structures.',
    startTime: '2026-04-22T13:30:00.000Z',
    endTime: '2026-04-22T16:00:00.000Z',
    participantCount: 1310,
    problems: [problemPool[1], problemPool[2]],
    isPublic: true,
    tags: ['graphs', 'bfs', 'dijkstra'],
  },
  {
    id: 'c4',
    title: 'DP Gauntlet',
    description: 'Pure dynamic programming from classic knapsack to interval DP and bitmask tricks.',
    startTime: '2026-04-23T10:00:00.000Z',
    endTime: '2026-04-23T13:00:00.000Z',
    participantCount: 744,
    problems: [problemPool[2], problemPool[3]],
    isPublic: true,
    tags: ['dynamic-programming', 'bitmask'],
  },
  {
    id: 'c5',
    title: 'Binary Blitz',
    description: 'Binary search on answer, search on functions, and predicates under pressure.',
    startTime: '2026-04-24T15:00:00.000Z',
    endTime: '2026-04-24T16:30:00.000Z',
    participantCount: 533,
    problems: [problemPool[0], problemPool[1]],
    isPublic: true,
    tags: ['binary-search', 'math'],
  },
  {
    id: 'c6',
    title: 'String Theory Cup',
    description: 'Hashing, KMP, Z-function, and suffix arrays in a strings-only battle.',
    startTime: '2026-04-25T09:00:00.000Z',
    endTime: '2026-04-25T11:30:00.000Z',
    participantCount: 419,
    problems: [problemPool[3], problemPool[0]],
    isPublic: true,
    tags: ['strings', 'hashing'],
  },
  {
    id: 'c7',
    title: 'Data Structures Duel',
    description: 'Segment trees, BITs, sparse tables, and persistent structures under the clock.',
    startTime: '2026-04-26T14:00:00.000Z',
    endTime: '2026-04-26T17:00:00.000Z',
    participantCount: 681,
    problems: [problemPool[2], problemPool[1], problemPool[0]],
    isPublic: true,
    tags: ['data-structures', 'segment-tree'],
  },
  {
    id: 'c8',
    title: 'Math Olympiad Round',
    description: 'Number theory, combinatorics, modular arithmetic, and prime sieves.',
    startTime: '2026-04-27T11:00:00.000Z',
    endTime: '2026-04-27T13:00:00.000Z',
    participantCount: 390,
    problems: [problemPool[0], problemPool[3]],
    isPublic: true,
    tags: ['math', 'number-theory'],
  },
  {
    id: 'c9',
    title: 'Greedy Games',
    description: 'Exchange arguments, interval scheduling, and activity selection problems.',
    startTime: '2026-04-28T16:00:00.000Z',
    endTime: '2026-04-28T17:30:00.000Z',
    participantCount: 298,
    problems: [problemPool[1], problemPool[3]],
    isPublic: true,
    tags: ['greedy', 'implementation'],
  },
  {
    id: 'c3',
    title: 'Creators Invitational',
    description: 'Private contest tooling benchmark for hosts.',
    startTime: '2026-04-29T09:00:00.000Z',
    endTime: '2026-04-29T11:00:00.000Z',
    participantCount: 226,
    problems: [problemPool[0], problemPool[2], problemPool[3]],
    isPublic: false,
    tags: ['mixed'],
  },
]

export const problems: Problem[] = problemPool

export const leaderboard: LeaderboardEntry[] = [
  { rank: 1,  user: users[2], score: 1150, solvedCount: 4, lastSubmission: '2026-04-22T18:08:00.000Z' },
  { rank: 2,  user: users[0], score: 980,  solvedCount: 3, lastSubmission: '2026-04-22T18:15:00.000Z' },
  { rank: 3,  user: users[6], score: 960,  solvedCount: 3, lastSubmission: '2026-04-22T18:17:00.000Z' },
  { rank: 4,  user: users[3], score: 920,  solvedCount: 3, lastSubmission: '2026-04-22T18:19:00.000Z' },
  { rank: 5,  user: users[1], score: 910,  solvedCount: 3, lastSubmission: '2026-04-22T18:20:00.000Z' },
  { rank: 6,  user: users[4], score: 870,  solvedCount: 2, lastSubmission: '2026-04-22T18:24:00.000Z' },
  { rank: 7,  user: users[5], score: 840,  solvedCount: 2, lastSubmission: '2026-04-22T18:27:00.000Z' },
  { rank: 8,  user: users[7], score: 790,  solvedCount: 2, lastSubmission: '2026-04-22T18:31:00.000Z' },
  { rank: 9,  user: users[8], score: 720,  solvedCount: 2, lastSubmission: '2026-04-22T18:35:00.000Z' },
  { rank: 10, user: users[9], score: 650,  solvedCount: 1, lastSubmission: '2026-04-22T18:40:00.000Z' },
]

export const currentUser: User = users[0]
